### ISSUE TITLE
Option to remove the E Icon in tab/icon bar 

### ISSUE THREAD

**Issue by a4z** [ProfileVisualization/easyview#1]
Hi, thanks for this extension, I like it.

Just one thing, it adds this fat big **E** int the statusbar / tab bar, in the upper right corner.

Since most of the time I do not need EasyView, it just wastes space, and destroys the layout of my git buttons, since it places itself in between.

![Screenshot 2022-03-08 at 11 47 52](https://user-images.githubusercontent.com/6172295/157224100-c121db18-57a6-4260-8fed-36031555647f.png)

It would be nice if I could remove the **E**, without removing the extension. Is that possible?

**Comment by xl10** [comment]
Yes. We can remove this icon and only use the right click on the file to open the profile. Thanks for the suggestion.

**Comment by xl10** [comment]
This is resolved.
